### PR TITLE
Fix TensorFlowFeatureBuilder ser/de and add tests, fix #110

### LINKED ISSUE #110: NPE on TensorFlowFeatureBuilder within Scio
If scio is upgraded to the current version of featran and the tf tests are run `sbt "project scio-tensorflow" test` you see the following error

```
[info] FeatureSpecJob
[info] - should work *** FAILED ***
[info]   org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.NullPointerException
[info]   at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:342)
[info]   at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:312)
[info]   at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:206)
[info]   at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:62)
[info]   at org.apache.beam.sdk.Pipeline.run(Pipeline.java:311)
[info]   at org.apache.beam.sdk.testing.TestPipeline.run(TestPipeline.java:353)
[info]   at org.apache.beam.sdk.testing.TestPipeline.run(TestPipeline.java:335)
[info]   at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:369)
[info]   at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:354)
[info]   at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:419)
[info]   ...
[info]   Cause: java.lang.NullPointerException:
[info]   at com.spotify.featran.tensorflow.package$TensorFlowFeatureBuilder.init(package.scala:28)
[info]   at com.spotify.featran.CrossingFeatureBuilder.init(CrossingFeatureBuilder.scala:90)
[info]   at com.spotify.featran.FeatureSet.featureValues(FeatureSpec.scala:300)
[info]   at com.spotify.featran.FeatureExtractor.$anonfun$featureResults$1(FeatureExtractor.scala:96)
[info]   at com.spotify.scio.util.Functions$$anon$7.processElement(Functions.scala:145)
[info]   ...
[info] MultiSpecJob
[info] - should work *** FAILED ***
[info]   org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.NullPointerException
[info]   at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:342)
[info]   at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:312)
[info]   at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:206)
[info]   at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:62)
[info]   at org.apache.beam.sdk.Pipeline.run(Pipeline.java:311)
[info]   at org.apache.beam.sdk.testing.TestPipeline.run(TestPipeline.java:353)
[info]   at org.apache.beam.sdk.testing.TestPipeline.run(TestPipeline.java:335)
[info]   at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:369)
[info]   at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:354)
[info]   at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:419)
[info]   ...
[info]   Cause: java.lang.NullPointerException:
[info]   at com.spotify.featran.tensorflow.package$TensorFlowFeatureBuilder.init(package.scala:28)
[info]   at com.spotify.featran.CrossingFeatureBuilder.init(CrossingFeatureBuilder.scala:90)
[info]   at com.spotify.featran.MultiFeatureSet.multiFeatureValues(FeatureSpec.scala:417)
[info]   at com.spotify.featran.MultiFeatureExtractor.$anonfun$featureResults$1(MultiFeatureExtractor.scala:73)
[info]   at com.spotify.scio.util.Functions$$anon$7.processElement(Functions.scala:145)
[info]   ...
```

Best current guess is that something is causing the underlying Features.Builder to get created and then needs serialization which doesn't happen because of the transient annotation.

### PR DESCRIPTION
**Pull request by nevillelyh**

### CODE REVIEW

File: tensorflow/src/main/scala/com/spotify/featran/tensorflow/package.scala [hunk 1]
```diff
@@ -23,9 +23,14 @@ import org.tensorflow.{example => tf}
 package object tensorflow {
 
   case class TensorFlowFeatureBuilder(
-    @transient private val underlying: Features.Builder = tf.Features.newBuilder())
+    @transient private var underlying: Features.Builder = tf.Features.newBuilder())
       extends FeatureBuilder[tf.Example] {
-    override def init(dimension: Int): Unit = underlying.clear()
+    override def init(dimension: Int): Unit = {
+      if (underlying == null) {
```
Comment (richwhitjr) [inline tensorflow/src/main/scala/com/spotify/featran/tensorflow/package.scala]: Would this only happen when the underlying object is created on the submitter side and accidentally serialized so we need to recreate it?

Comment (nevillelyh) [reply tensorflow/src/main/scala/com/spotify/featran/tensorflow/package.scala]: Yes the instance is almost always created on the driver/`main` side and ser/de-ed into workers.
